In [1]:
import numpy as np

In [2]:
# 1차원 배열
vec = np.array([1, 2, 3, 4, 5])
print(vec)

[1 2 3 4 5]


In [3]:
# 2차원 배열
mat = np.array([[10, 20, 30], [ 60, 70, 80]]) 
print(mat)

[[10 20 30]
 [60 70 80]]


In [4]:
print('vec의 타 입 :',type(vec)) 
print('mat의 타 입 :',type(mat))

vec의 타 입 : <class 'numpy.ndarray'>
mat의 타 입 : <class 'numpy.ndarray'>


In [5]:
print('vec의 축의 개수 :',vec.ndim)# 축의 개수 출력 
print('vec의 크 기(shape) :',vec.shape) # 크 기 출 력

vec의 축의 개수 : 1
vec의 크 기(shape) : (5,)


In [6]:
print('mat의 축의 개수 :',mat.ndim)# 축의 개수 출력 
print('mat의 크 기(shape) :',mat.shape) # 크 기 출 력

mat의 축의 개수 : 2
mat의 크 기(shape) : (2, 3)


In [7]:
#모든 값이 0인2x3배열 생성. 
zero_mat = np.zeros((2,3)) 
print(zero_mat)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
#모든 값이 1인 2x3배열 생성. 
one_mat = np.ones((2,3)) 
print(one_mat)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# 모든 값이 특정 상수인 배열 생성.이 경우 7. 
same_value_mat = np.full((2,2), 7) 
print(same_value_mat)

[[7 7]
 [7 7]]


In [10]:
#대각선 값이 1이고 나머지 값이 0인 2차원 배열을 생성. 
eye_mat = np.eye(3)
print(eye_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#임의의 값으로 채워진 배열 생성 
random_mat=np.random.random((2,2))# 임의의 값으로 채워진 배열 생성 
print(random_mat)

[[0.84928304 0.73248967]
 [0.17180425 0.35210083]]


In [17]:
#0부터 9까지 np.arrange(n)은 0부터 n-1까지의 값을 가지는 배열을 생성한다.
range_vec = np.arange(10) 
print(range_vec)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
#1부터 9까지 +2씩 적용되는 범위
n=2
range_n_step_vec = np.arange(1, 10, n) 
print(range_n_step_vec)

[1 3 5 7 9]


In [19]:
reshape_mat = np.array(np.arange(30)).reshape((5,6)) 
print(reshape_mat)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


위 식: np.reshape()은 내부 데이터는 변경하지 않으면서 배열의 구조를 바꿉니다. 0부터 29까지의 숫자를 생성하는 arange(30)을 수행한 후, 원소의 개수가 30가 이므로 5행 6열의 행렬로 변경합니다.

In [20]:
mat = np.array([[1, 2, 3], [4, 5, 6]]) 
print(mat)

[[1 2 3]
 [4 5 6]]


In [21]:
#첫 번째 행 출력 
slicing_mat = mat[0, :] 
print(slicing_mat)

[1 2 3]


In [22]:
#두 번째 행 출력 
slicing_mat = mat[:, 1] 
print(slicing_mat)

[2 5]
